### ISSUE TITLE
Linker Error on Cygwin

### ISSUE THREAD

**Issue by hbast** [auerswal/ssocr#2] opened 2017-09-27 15:12 UTC
Hey there,
I'm trying to compile ssocr under Cygwin x64 and ran into the following problem:
```
$ make
cc -D_FORTIFY_SOURCE=2 -Wall -W -Wextra -pedantic -Werror -pedantic-errors -fstack-protector-all  -O3   -c -o ssocr.o ssocr.c
cc -D_FORTIFY_SOURCE=2 -Wall -W -Wextra -pedantic -Werror -pedantic-errors -fstack-protector-all  -O3   -c -o imgproc.o imgproc.c
cc -D_FORTIFY_SOURCE=2 -Wall -W -Wextra -pedantic -Werror -pedantic-errors -fstack-protector-all  -O3   -c -o help.o help.c
cc   ssocr.o imgproc.o help.o  -lm -lImlib2 -o ssocr
ssocr.o:ssocr.c:(.rdata$.refptr.__stack_chk_guard[.refptr.__stack_chk_guard]+0x0): undefined reference to `__stack_chk_guard'
imgproc.o:imgproc.c:(.text+0x2e): undefined reference to `__stack_chk_fail'
imgproc.o:imgproc.c:(.text+0x2e): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `__stack_chk_fail'
imgproc.o:imgproc.c:(.text+0x6e): undefined reference to `__stack_chk_fail'
imgproc.o:imgproc.c:(.text+0x6e): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `__stack_chk_fail'
imgproc.o:imgproc.c:(.text+0x106): undefined reference to `__stack_chk_fail'
imgproc.o:imgproc.c:(.text+0x106): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `__stack_chk_fail'
imgproc.o:imgproc.c:(.text+0x1cc): undefined reference to `__stack_chk_fail'
imgproc.o:imgproc.c:(.text+0x1cc): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `__stack_chk_fail'
imgproc.o:imgproc.c:(.text+0x255): undefined reference to `__stack_chk_fail'
imgproc.o:imgproc.c:(.text+0x255): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `__stack_chk_fail'
imgproc.o:imgproc.c:(.text+0x2d5): more undefined references to `__stack_chk_fail' follow
imgproc.o:imgproc.c:(.text+0x2d5): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `__stack_chk_fail'
imgproc.o:imgproc.c:(.text+0x394): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `__stack_chk_fail'
imgproc.o:imgproc.c:(.text+0x813): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `__stack_chk_fail'
imgproc.o:imgproc.c:(.text+0x84f): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `__stack_chk_fail'
imgproc.o:imgproc.c:(.text+0x88f): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `__stack_chk_fail'
imgproc.o:imgproc.c:(.text+0x985): additional relocation overflows omitted from the output
collect2: Fehler: ld gab 1 als Ende-Status zurück
make: *** [<eingebaut>: ssocr] Fehler 1
```
Here some information about the installed util and lib versions:
```
GNU ld (GNU Binutils) 2.29.51.20170708

$ gcc -v
Es werden eingebaute Spezifikationen verwendet.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-cygwin/6.4.0/lto-wrapper.exe
Ziel: x86_64-pc-cygwin
Konfiguriert mit: /cygdrive/i/szsz/tmpp/gcc/gcc-6.4.0-1.x86_64/src/gcc-6.4.0/configure --srcdir=/cygdrive/i/szsz/tmpp/gcc/gcc-6.4.0-1.x86_64/src/gcc-6.4.0 --prefix=/usr --exec-prefix=/usr --localstatedir=/var --sysconfdir=/etc --docdir=/usr/share/doc/gcc --htmldir=/usr/share/doc/gcc/html -C --build=x86_64-pc-cygwin --host=x86_64-pc-cygwin --target=x86_64-pc-cygwin --without-libiconv-prefix --without-libintl-prefix --libexecdir=/usr/lib --enable-shared --enable-shared-libgcc --enable-static --enable-version-specific-runtime-libs --enable-bootstrap --enable-__cxa_atexit --with-dwarf2 --with-tune=generic --enable-languages=ada,c,c++,fortran,lto,objc,obj-c++ --enable-graphite --enable-threads=posix --enable-libatomic --enable-libcilkrts --enable-libgomp --enable-libitm --enable-libquadmath --enable-libquadmath-support --enable-libssp --enable-libada --disable-symvers --with-gnu-ld --with-gnu-as --with-cloog-include=/usr/include/cloog-isl --without-libiconv-prefix --without-libintl-prefix --with-system-zlib --enable-linker-build-id --with-default-libstdcxx-abi=gcc4-compatible
Thread-Modell: posix
gcc-Version 6.4.0 (GCC)

imlib2 incl. devel in Version 1.4.9

libX11 incl. devel in Version 1.6.5
```

If you need further information, give me a hint ;-)

Thx & Bye,
Holger

**Comment by hbast** [comment] 2017-09-27 16:28
Ok, I solved the problem for me:
The error is gone after removing the "-fstack-protector-all" flag in the Makefile.

**Comment by auerswal** [comment] 2017-10-01 13:09
Hi,

the stack protection feature of GCC seems to have changed... you might need to add '-lssp' to the LDLIBS variable in the Makefile to use it, i.e. compile with '-fstack-protector-all'.

I am still using GCC 4.x on an older GNU/Linux distribution, thus I cannot test this myself. If you want to test this, please report back if it works.

Thanks,
Erik

**Comment by auerswal** [comment] 2017-10-14 13:10
I'll keep this issue open, because I think it could be relevant for everybody using a recent GCC compiler.

**Comment by auerswal** [comment] 2018-07-22 18:14
I have not been able to reproduce the problems on GNU/Linux. Compiling ```ssocr``` works without problems on Debian 9.5 (*Stretch*) with gcc 6.3.0 and Ubuntu 18.04 LTS with gcc version 7.3.0, as well as the older GNU/Linux distributions I have used before. Thus this is not a common problem with newer gcc versions.

This problems seems to be specific to the Cygwin version used.

Thus I am closing this issue here.

**Closed as completed by auerswal** 2018-07-22 18:14 UTC
Labels: question
